/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  use: [{ type: "autogenerated", dirName: "use" }],
  dev: [
    "dev/dev",
    "dev/background",
    "dev/cloudcat",
    "dev/subscribe",
    "dev/config",
    "dev/api",
    "dev/cat-api",
    {
      type: "category",
      label: "Agent 智能助手",
      link: { type: "doc", id: "dev/agent/agent" },
      items: [
        "dev/agent/agent-conversation",
        "dev/agent/agent-dom",
        "dev/agent/agent-skill-install",
        "dev/agent/agent-skill",
        "dev/agent/agent-task",
        "dev/agent/agent-model",
        "dev/agent/agent-opfs",
        "dev/agent/agent-mcp",
        "dev/agent/agent-skill-dev",
        "dev/agent/agent-builtin-tools",
      ],
    },
    "dev/meta",
  ],
  change: [{ type: "autogenerated", dirName: "change" }],
};

module.exports = sidebars;
